# Site settings
title: Patrick Hanus - Developer & Designer
description: "A blog about lorem ipsum ..."
baseurl: "https://patrickhanus.com"
url: "http://patrickhanus.com"
cover: "/assets/cover.png"
logo: "/assets/logo.png"

# User settings
username: Patrick Hanus
user_title: Patrick Hanus | Designer & Developer
email: patrick@skymse.com
twitter_username: "@thehsedition"
github_username:  "@thehsedition"
gplus_username:  "@thehsedition"
disqus_username: "@thehsedition"

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# sass/css minify
#sass:
#    style: compressed

exclude: [README.md, CHANGELOG.md]
include: ["_pages", "_projects"]
permalink: /:title/

# Links to include in menu navigation
links:
  - title: Home
    url: /
    img: resume-profile-picture.jpg
  - title: Resume
    url: /resume.html
    img: resume-profile-picture.jpg
  - title: Lists
    url: /lists.html
    img: 
  - title: Blog
    url: /blog.html
    img: 
  - title: Projects
    url: /projects.html
    img: 
  - title: About
    url: /about.html
    img: 

# projects in header index
projects:
  - name: Skymouse Studios
    url: /skymouse.html
    img: project-willys-farm.jpg
  - name: RESOURCE Commercial Real Estate
    url: /resource.html
    img: project-willys-farm.jpg
  - name: Other People's Lives
    url: /resource.html
    img: project-willys-farm.jpg
  - name: Man The Movie
    url: /man-the-movie.html
    img: project-willys-farm.jpg

# Links to Social Media
social: 
  - name: Spotify
    url: http://bit.ly/ph-spotify
  - name: Instagram
    url: http://bit.ly/ph-insta
  - name: Vimeo
    url: http://bit.ly/ph-vimeo
  - name: LinkedIn
    url: http://bit.ly/ph-LinkedIn
  - name: Dribbble
    url: http://bit.ly/ph-dribbble
  - name: YouTube
    url: http://bit.ly/ph-youtube
  - name: GitHub
    url: http://bit.ly/ph-github
  - name: Twitter
    url: http://bit.ly/ph-twitter

# Descriptions for Blog Categories
descriptions:
  - cat: Life
    desc: "Things that make life better."

  - cat: Code
    desc: "Developing a better me"